### ISSUE TITLE
[feature request] Context up to a matching pattern instead of by fixed number of lines

### ISSUE THREAD

**Issue by amosshapira** [BurntSushi/ripgrep#2766]
I'd like to be able to print all lines starting/surrounding (aka "context") a matching line up to another matching pattern, rather than a fixed number of lines.

For instance, given I have a tree with [docker-compose.yml](https://docs.docker.com/compose/compose-file/compose-file-v3/) files and I'm looking for an example standza, e.g.:
```

  envvars:
    image: dkr.ecr.amazonaws.com/envvars:0.1.2
    env_file: .env
    working_dir: /work
    volumes:
      - .:/work

```
I can search through the tree with:
```
rg -A 10 -g docker-compose\* envvars:
```
And get up to 10 lines after the matching `envvars:` line but instead I'd like `rg` to output only up to the next empty line.

A possible suggestion for the flag: to avoid adding more flags, perhaps make the line number parameter of the existing `-A`/`-B`/`-C` flags accept a string e.g. '-A /\n/' to indicate that the context is defined by a pattern rather than a fixed number of lines.
